# Generated by Django 6.0.1 on 2026-02-01 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='LearnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('middle_image', models.ImageField(blank=True, null=True, upload_to='learn_items/middle/')),
                ('object_image', models.ImageField(blank=True, null=True, upload_to='learn_items/objects/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='learn_items/audio/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lets_learn.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
