# Generated by Django 6.0.1 on 2026-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnitem',
            old_name='content',
            new_name='content_name',
        ),
        migrations.RemoveField(
            model_name='learnitem',
            name='middle_image',
        ),
        migrations.AlterField(
            model_name='learnitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
