# Generated by Django 6.0.1 on 2026-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_learn', '0002_rename_content_learnitem_content_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='learnitem',
            index=models.Index(fields=['category', 'order'], name='lets_learn__categor_b77cf9_idx'),
        ),
    ]
