# Generated by Django 6.0.1 on 2026-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_learn', '0003_learnitem_lets_learn__categor_b77cf9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnitem',
            name='category',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Section 1'),
                    (2, 'Section 2'),
                    (3, 'Section 3'),
                    (4, 'Section 4'),
                    (5, 'Section 5'),
                    (6, 'Section 6'),
                    (7, 'Section 7'),
                    (8, 'Section 8'),
                    (9, 'Section 9'),
                    (10, 'Section 10'),
                    (11, 'Section 11'),
                    (12, 'Section 12'),
                    (13, 'Section 13'),
                    (14, 'Section 14'),
                ],
                db_column='category_id',
            ),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
