# Generated by Django 6.0.1 on 2026-02-02 00:10

from django.db import migrations, models


def create_category_configs(apps, schema_editor):
    CategoryConfig = apps.get_model('lets_learn', 'CategoryConfig')
    for value in range(1, 15):
        CategoryConfig.objects.get_or_create(
            category=value,
            defaults={"name": f"Section {value}"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lets_learn', '0004_category_enum'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryConfig',
            fields=[
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Section 1'), (2, 'Section 2'), (3, 'Section 3'), (4, 'Section 4'), (5, 'Section 5'), (6, 'Section 6'), (7, 'Section 7'), (8, 'Section 8'), (9, 'Section 9'), (10, 'Section 10'), (11, 'Section 11'), (12, 'Section 12'), (13, 'Section 13'), (14, 'Section 14')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category'],
            },
        ),
        migrations.RunPython(create_category_configs, migrations.RunPython.noop),
    ]
