# Generated by Django 6.0.1 on 2026-02-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_learn', '0005_category_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnitem',
            name='object_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
