# Generated by Django 6.0.1 on 2026-02-02 00:30

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    CategoryConfig = apps.get_model('lets_learn', 'CategoryConfig')
    LearnItem = apps.get_model('lets_learn', 'LearnItem')

    for category in CategoryConfig.objects.all():
        if category.name and not category.slug:
            category.slug = slugify(category.name, allow_unicode=True)
            category.save(update_fields=['slug'])

    for item in LearnItem.objects.all():
        if item.name and not item.slug:
            item.slug = slugify(item.name, allow_unicode=True)
            item.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('lets_learn', '0006_learnitem_object_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryconfig',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learnitem',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120),
        ),
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
    ]
