# Generated by Django 6.0.1 on 2026-02-02 00:40

from django.db import migrations
from django.utils.text import slugify


CATEGORY_NAMES = {
    1: "Your first alphabets",
    2: "Let's learn Nepali",
    3: "Math is fun with us",
    4: "Nepali months",
    5: "English Months",
    6: "7 days",
    7: "4 seasons",
    8: "Colors",
    9: "Animals",
    10: "Human Body",
    11: "Birds",
    12: "Punctuation Marks",
    13: "World meaning",
    14: "Shapes",
}


def update_category_configs(apps, schema_editor):
    CategoryConfig = apps.get_model('lets_learn', 'CategoryConfig')

    for category_id, name in CATEGORY_NAMES.items():
        slug = slugify(name, allow_unicode=True)
        CategoryConfig.objects.update_or_create(
            category=category_id,
            defaults={
                "name": name,
                "slug": slug,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lets_learn', '0007_add_slugs'),
    ]

    operations = [
        migrations.RunPython(update_category_configs, migrations.RunPython.noop),
    ]
