# Generated by Django 6.0.1 on 2026-02-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_learn', '0008_update_category_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryconfig',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Your first alphabets'), (2, "Let's learn Nepali"), (3, 'Math is fun with us'), (4, 'Nepali months'), (5, 'English Months'), (6, '7 days'), (7, '4 seasons'), (8, 'Colors'), (9, 'Animals'), (10, 'Human Body'), (11, 'Birds'), (12, 'Punctuation Marks'), (13, 'World meaning'), (14, 'Shapes')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learnitem',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Your first alphabets'), (2, "Let's learn Nepali"), (3, 'Math is fun with us'), (4, 'Nepali months'), (5, 'English Months'), (6, '7 days'), (7, '4 seasons'), (8, 'Colors'), (9, 'Animals'), (10, 'Human Body'), (11, 'Birds'), (12, 'Punctuation Marks'), (13, 'World meaning'), (14, 'Shapes')], db_column='category_id'),
        ),
    ]
