# Generated by ChatGPT on 2026-02-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lets_learn', '0009_alter_categoryconfig_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryconfig',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Your first alphabets'), (2, "Let's learn Nepali"), (3, 'Math is fun with us'), (4, 'Nepali months'), (5, 'English Months'), (6, '7 days'), (7, '4 seasons'), (8, 'Colors'), (9, 'Animals'), (10, 'Human Body'), (11, 'Birds'), (12, 'Punctuation Marks'), (13, 'World meaning'), (14, 'Shapes')], unique=True),
        ),
        migrations.AlterField(
            model_name='learnitem',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lets_learn.categoryconfig', to_field='category'),
        ),
    ]
