# Generated by Django 6.0.1 on 2026-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_learn', '0010_use_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
